# Generated by Django 5.2.7 on 2025-12-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_catalogo', to='catalogo.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default='servicios/default.jpg', upload_to='servicios/', verbose_name='Imagen'),
        ),
    ]
