# Generated by Django 3.2.19 on 2025-10-06 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('estado', models.CharField(choices=[('1', 'Pendiente'), ('2', 'En Proceso'), ('3', 'Completado'), ('4', 'Cancelado'), ('5', 'Devuelto')], default='1', max_length=1, verbose_name='Estado')),
                ('tipo_venta', models.CharField(choices=[('p', 'Producto')], default='p', max_length=1, verbose_name='Tipo de Venta')),
                ('monto_total', models.PositiveIntegerField(verbose_name='Monto Total')),
                ('usuario', models.ForeignKey(limit_choices_to={'estado': '1'}, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.PositiveIntegerField(verbose_name='Precio Unitario')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalles Ventas',
                'db_table': 'detalle_ventas',
            },
        ),
    ]
