# Generated by Django 5.2.7 on 2025-12-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_imagen_alter_producto_servicio_and_more'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_web_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_inventario', to='catalogo.categoria', verbose_name='Categoría Web'),
        ),
        migrations.AddField(
            model_name='producto',
            name='servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_inventario', to='catalogo.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria_id',
            field=models.ForeignKey(limit_choices_to={'estado': '1'}, on_delete=django.db.models.deletion.PROTECT, to='catalogue.categoria', verbose_name='Categoría Inventario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
