# Generated by Django 3.2.19 on 2025-10-06 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo Usuario',
                'verbose_name_plural': 'tipos Usuarios',
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=45, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=45, verbose_name='Apellido Materno')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('contrasenia', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{9,}$', message='Debe tener al menos 9 caracteres, una mayúscula y un símbolo especial.')])),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('tipo_usuario', models.ForeignKey(limit_choices_to={'estado': '1'}, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
